CREATE TABLE IF NOT EXISTS "job" (
  "id" BIGSERIAL PRIMARY KEY,
  "app_name" TEXT NOT NULL,
  "state" TEXT NOT NULL,
  "attributes" HSTORE NULL DEFAULT NULL,
  created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT now(),
  updated_at TIMESTAMP WITHOUT TIME ZONE NULL DEFAULT NULL
);


CREATE TABLE IF NOT EXISTS "item" (
  "id" TEXT NOT NULL,
  "job_id" BIGINT NOT NULL REFERENCES job(id) ON DELETE CASCADE,
  "status" TEXT NOT NULL,
  "attributes" HSTORE NULL DEFAULT NULL,
  created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT now(),
  updated_at TIMESTAMP WITHOUT TIME ZONE NULL DEFAULT NULL,
  PRIMARY KEY("id", "job_id")
);